theme: jekyll-theme-slate
url: "https://ym-rakennettu-ymparisto.github.io/kaavatietomalli" # the base hostname & protocol for your site
home: "https://ym-rakennettu-ymparisto.github.io/kaavatietomalli"
plugins:
  - jekyll-sitemap
repository: YM-rakennettu-ymparisto/kaavatietomalli
plugins:
- jekyll-sitemap
- kramdown


