theme: jekyll-theme-slate
url: "https://koivusto.github.io/Tonttitietomalli/" # the base hostname & protocol for your site
home: "https://koivusto.github.io/Tonttitietomalli/"
plugins:
  - jekyll-sitemap
repository: Koivusto/Tonttitietomalli
google_analytics: 
plugins:
- jekyll-sitemap
- kramdown
default_modelversion: '1.0'


